### ISSUE TITLE
Tracing for existing applications?

### ISSUE THREAD

**Issue by matthias3333** [gvanem/wsock-trace#18]
Dear Gisle Vanem,

is it possible to use your tool for existing applications without relinking to your library?

**Comment by gvanem** [comment]
Not at the moment.

**Comment by matthias3333** [comment]
Thank you. :)

If anybody knows similar tools that work without recompilation of applications and operate on socket level, please let me know. :)

**Comment by gvanem** [comment]
This project shows how it could be done: https://github.com/valinet/network-load-balancer
