### ISSUE TITLE
HELP request

### ISSUE THREAD

**Issue by oppybob** [gvanem/wsock-trace#2]
mine is a help request
I'm trying to use wsock_trace with vs2013
the WSAStartup call fails because it cannot find the address of WSAStartup !
What am I missing ?
![image](https://cloud.githubusercontent.com/assets/12172742/15207807/a49cb784-1828-11e6-93f0-f01d2e0dcb68.png)

best regards
bob

**Comment by gvanem** [comment]
Start by increasing the `trace_level` to e.g. `2`. Then (if running in cmd) you should see where `ws2_32.dll` is located. Like:
```
  stkwalk.c(585): GetModuleListTH32(): Enumerated 20 modules:
  stkwalk.c(591):   Module                                                       Baseaddr       Size
    ----------------------------------------------------------------------------------------------------
  stkwalk.c(606):   F:\gv\VC_project\ws_trace\src\test.exe                       0x00D50000     316 kB.
  ...
  stkwalk.c(606):   C:\WINDOWS\SYSTEM32\ws2_32.dll                               0x74AA0000     380 kB.
```
Put the `trace_level = 2` in the `%APPDATA%\wsock_trace` file.

Failing that, increase to `4` and you'll get some trace like:
```
  common.c(237):  0: Module 0x74AA0000/ws2_32.dll, func "WSAStartup" -> 0x74AA6520.
  ...
```

A `ws2_32.dll` without a `WSAStartup` should *not* be possible. But I'm not sure how you have created or how you're running your program.

**Comment by oppybob** [comment]
resolved
it was a mismatch in UNICODE settings
thanks
