### ISSUE TITLE
NMAKE : fatal error U1073: don't know how to make 'MSVC_obj\cpu.obj'

### ISSUE THREAD

**Issue by sgeto** [gvanem/wsock-trace#3]
I think the .c file is just missing.
Also: is it a good idea to disable LUA?

**Comment by gvanem** [comment]
Thanks for reporting. Fixed in https://github.com/gvanem/wsock-trace/commit/13fc64020cf097cda271dd09fbe8cf91d2a77e1e

LUA is far from finished. Hence I've disabled it in `Makefile.vc6` by default. Feel free to contribute if you know LUA more than I do.

**Comment by sgeto** [comment]
I may do so soon. I'm in the middle of getting my head around it...

**Comment by sgeto** [comment]
actually, LUA doesn't seem to be disabled:

`NMAKE : fatal error U1073: don't know how to make 'f:\MingW32\src\Parsers\LuaJIT/src/lua.h'`

why would it still ask for it?

**Comment by gvanem** [comment]
Because of the last lines in Makefile.vc6. Try this:
```
--- a/src/Makefile.vc6
+++ b/src/Makefile.vc6
@@ -207,10 +207,12 @@ $(OBJ_DIR)\wsock_trace.obj: wsock_trace.c common.h stkwalk.h in_addr.h \

 $(OBJ_DIR)\wsock_trace_lua.obj: wsock_trace_lua.c common.h init.h wsock_trace_lua.h

-wsock_trace_lua.h:          $(LUAJIT_ROOT)/src/lua.h     \
-                            $(LUAJIT_ROOT)/src/luaconf.h \
-                            $(LUAJIT_ROOT)/src/lualib.h  \
-                            $(LUAJIT_ROOT)/src/lua.h     \
-                            $(LUAJIT_ROOT)/src/lauxlib.h
+!if "$(USE_LUA)" == "1"
+wsock_trace_lua.h: $(LUAJIT_ROOT)/src/lua.h     \
+                   $(LUAJIT_ROOT)/src/luaconf.h \
+                   $(LUAJIT_ROOT)/src/lualib.h  \
+                   $(LUAJIT_ROOT)/src/lua.h     \
+                   $(LUAJIT_ROOT)/src/lauxlib.h
+!endif
```

Or I'll just remove those last lines.

**Comment by sgeto** [comment]
Wouldn't removing those last lines break lua scripting capabilities if I'd set lua to 1 some time in the future?

**Comment by gvanem** [comment]
Well, possibly. But I assume the `$(LUAJIT_ROOT)/src/*.h` are older than the `wsock_trace` files.

**Comment by sgeto** [comment]
I'm not sure I'm following. 
But trying a little more I'm realizing that lua support has a long way to go anyways. Maybe this error message helps you in some way:

```
wsock_trace_lua.c(122): error C2079: 'wstrace_lua_table' uses undefined struct 'luaL_reg'
wsock_trace_lua.c(126): fatal error C1903: unable to recover from previous error(s); stopping compilation
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
```


Also: There are a few minor fixes in Makefile.vc6 necessary to make the install part of the build go smoothly:

- `$(VCINSTALLDIR)` by default already includes a backslash at the end. So `$(VCINSTALLDIR)\lib` will have two. 
-  if the path `$(LIB_TARGET)` includes spaces (e. g "Program Files (x86"), the copy command will fail unless enclosed it with qoutes
- in case lua gets to work, it might also be worth considering replace the UNIX forward-slashes in `$(LUAJIT_ROOT)/src/*.h` with backslashes because `$(LUAJIT_ROOT)` is a Windows path

I may do a pull request. Would be my first...

**Comment by gvanem** [comment]
I don't know about compiler error. `luaL_reg` (or `luaL_Reg`) is plainly defined in LuaJit's `lauxlib.h`.
But maybe you have used standard Lua 5.x or another LuaJit version?

**Comment by sgeto** [comment]
I did. Silly me. I check again...

**Comment by sgeto** [comment]
hey, it's been a while. Lua bindings are fine so far. I of course more testing. I get into that once I get better with lua.
I noticed that a executable called "test.exe" is created during the build. But I can't seem to get it to run. The makefile also indicates that there are other executables that can be created (geoip.exe, ect.)
And how do I produce them and how to execute "test.exe"?

**Comment by gvanem** [comment]
Did you read the section **Configuration**?
 *The trace-level and other settings are controlled by a config-file wsock_trace....*

Just do:
```
nmake -f Makefile.vc6 geoip.exe geoip2.exe
```

**Comment by gvanem** [comment]
PS. I should have made a `make help` target to print out the possible targets in a Makefile. But I feel Nmake is so limited and lame compared to GNU-make. So I was thinking of rewriting the Makefiles using GNU-make **only**. Would that be fine with you? 

Preferably only **one** Makefile targeting all compilers; e.g. use `make TARGET=MSVC all`.

It's a long time since I've updated the `*.vcxproj` files since I don't use Visual-Studio anymore.

**Comment by sgeto** [comment]
Pretty impressive if you're seriously thinking on typing out a universal makefile.  Luckily, wsock-trace doesn't have any third party dependencies-that would be a nightmare.

I found VS from day one incredibly bloated, but getting GNUmake to always play well may be a challenge as well. I am just worried that with every other change in the source, the makefile(s) would need to be adjusted as well...

Go for it. I'll test. 

A little unrelated but what was also weird earlier was that %HOME% is not normally set in windows. Instead %HOMEPATH% or %USERPROFILE% point to the user's home directory on any windows machine.

**Comment by gvanem** [comment]
So you didn't have `%APPDATA%` either? Was it the reason `test.exe` didn't show anything?
Besides `%USERPROFILE%` and `%APPDATA%` points to different directories.

**Comment by sgeto** [comment]
Yes that was the reason. I have %APPDATA% but I didn't place the config file and dll there. Test.exe was looking for the files using the nonexsisting ℅HOME℅ variable. Once I created it, everything worked. 
Except for geoip2.exe. It sadly doesn't build at all.

**Comment by gvanem** [comment]
Ok. Open up another issue and tell what's wrong.

PS. the .DLL doesn't have to be in the same place. Anywhere on `PATH` should be okay.

**Comment by sgeto** [comment]
strange. I can't seem to reproduce the test.exe error. Did you change something in this regard?

**Comment by gvanem** [comment]
Since I don't know what the `test.exe` error was, so no.
