### ISSUE TITLE
init.c something something

### ISSUE THREAD

**Issue by sgeto** [gvanem/wsock-trace#6]
Hey, 

Me lazy. Checkout this screenshot. Is that just me?

![capture](https://cloud.githubusercontent.com/assets/8343121/23829992/80ca6d6a-0710-11e7-918c-82c615c3848a.PNG)

**Comment by gvanem** [comment]
My bad. I had lots of local changes just waiting for a `git push`.  The compile-error in `init.c` should be fixed by this push: https://github.com/gvanem/wsock-trace/commit/22c5e082010ea4a15d84338b6fd778a0087ff83c.

**Comment by sgeto** [comment]
yep all good!
thanks
